### ISSUE TITLE
psutil v. 3 compatibility

### ISSUE THREAD

**Issue by BenjaminBossan** [ottogroup/palladium#14]
The /alive call does not work with psutil v. 3 upwards because it seems the _get_memory_info_ method does no longer exist. A fix would be welcome.

**Comment by dnouri** [comment]
Is there a corresponding method for psutil 3?

**Comment by BenjaminBossan** [comment]
Idk whether it returns the same information, but this could be a replacement:
http://pythonhosted.org/psutil/index.html?highlight=memory%20info#psutil.Process.memory_info

**Comment by alattner** [comment]
We updated the dependencies in the Palladium release 1.0.1. psutil's memory_info is now used.
