### ISSUE TITLE
config's model entry is not updated after a model is loaded or updated

### ISSUE THREAD

**Issue by alattner** [ottogroup/palladium#18]
When accessing `get_config()['model']` you might not get the current active model as the config is not updated after loading or updating models. If a prediction server is started, you will get an instantiated model object as specified in the model section of the config.

/alive and /predict entry points are still using the correct active model.

Current workaround for the CachedUpdatePersister to get the active model is to use the process_store in palladium.util as it is updated by the CachedUpdatePersister:

```
from palladium.util get process_store
process_store.get('model')
```

**Comment by dnouri** [comment]
As far as I can tell, `get_config()['model']` will never give you a trained model.  I guess you might expect that it gives you that.  But the way to get a trained model is to use `get_config()['model_persister'].read()`.  This in turn will, for the `CachedUpdatePersister`, access `process_store` as you mention.

However, as far as I can tell, this is consistent with all other configuration values: The configuration is never changed after it's initialized.

**Comment by alattner** [comment]
I added a section `How can I access the active model in my code?` to the FAQ
