### ISSUE TITLE
Avoid delayed initialization using other WSGI servers

### ISSUE THREAD

**Issue by alattner** [ottogroup/palladium#25]
1) If Palladium is started with the pld-devserver script, the initialization (initialize_config) is run directly before exposing the service. Using gunicorn with Palladium leads to a delayed initialization, i.e., initialize_config will not be run before the first request has arrived. This can lead to bad response times for first requests after start-up.

2) Another observation is that pld-devserver binds the port when the service is up and running whereas gunicorn (at least in default setting) binds the port early and incoming requests are blocked until Palladium's initialization has finished.

To solve the first issue, it would be possible to run initialize_config() directly in the module to harmonize the behavior, but due to some dependencies during start-up phase I haven't found a very elegant solution yet. (Multiple initialize_config calls would happen then if the pld-fit / pld-test / etc. scripts are run.)

**Comment by alattner** [comment]
@dnouri: Do you have an idea for a good place for initialize_config in a way that the fit-mode scripts still trigger it the function first (otherwise the CachedUpdatePersister thread would also be started in the non-server modes like pld-fit, pld-test, ...)? Or any other idea to handle the start-up phase?

**Comment by dnouri** [comment]
@alattner I think one way is to create a new module `palladium.wsgi` or some such and there have:

```python
from .util import initialize_config
from .server import app

initialize_config()
```

Then: `gunicorn palladium.wsgi:app`.  This should address your problem by initializing on startup, yes?

**Comment by alattner** [comment]
@dnouri: I also had this as a second solution in mind but when looking at the new module's implementation, I felt like there must be something better. As you came up with the same idea, maybe it's not that bad. Anyway, I prefer it to the other solution where initialize_config() is put at the end (or middle) of server.py and where more intervention is needed to allow multiple calls of initialize_config().
