### ISSUE TITLE
How do i use, with a pretrained skorch/pytorch model ?

### ISSUE THREAD

**Issue by Avhirup** [ottogroup/palladium#90]
I already have an skorch/pytorch model pickled into a file, How do I use it without the need of retraining or prototyping? and just use the palladium dev-server? 
Also, Does it support handling multiple requests in parallel?

**Comment by alattner** [comment]
You should be able to use your model if you manually add it to a Palladium model persister, e.g., to the File persister. You have to configure your model persister as desired. If you gzip and rename your existing model to `model-1.pkl.gz`, you will have to use these settings:
```
# config.py
'model_persister': {
    '__factory__': 'palladium.persistence.CachedUpdatePersister',
    'impl': {
        '__factory__': 'palladium.persistence.File',
        'path': 'model-{version}.pickle',
        },
    },
```
```
# model-metadata.json 
{
    "models": [
        {
            "train_timestamp": "2018-12-13T16:09:28.087847",
            "version": 1
        }
    ],
    "properties": {
        "db-version": "1.2.1.1",
        "active-model": "1"
    }
}
```
Flask's devserver should not be used for production settings (see http://flask.pocoo.org/docs/1.0/deploying/). How to use Palladium with gunicorn is described here: https://palladium.readthedocs.io/en/latest/user/deployment.html#web-server-installation

**Comment by Avhirup** [comment]
Thanks Andreas, I ll try it out.
